source "https://rubygems.org"
gem "pry-debugger", :group => "development"
gem "sinatra"
gem "haml"
gem "unicorn", :group => "production"
gem "omniauth"
gem "omniauth-google-oauth2"
gem "tilt"
gem "erubis"
