source 'https://rubygems.org'
gem 'sinatra'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem 'tilt'
gem 'erubis'
gem 'activerecord'
gem 'sqlite3', :group => 'development'
gem 'pg', :group => 'production'
gem 'sass'
gem 'haml'
gem 'coffee-script'
gem 'airbrake', :group => 'production'
gem 'thin', :group => 'production'
gem 'sshkit', '~> 1.0.0' # fix https://github.com/capistrano/sshkit/issues/39
gem 'capistrano', '~> 2.15.4'
