-
  name: integer literal
  form: numvar = num
  example: seconds_in_hour = 3600
  output: number
  inputs: number
-
  name: float literal
  form: numvar = num
  example: pi = 3.14
  output: number
  inputs: number
-
  name: addition
  tags: plus
  form: numvar = num + num
  example: assets = liabilities + equity
  output: number
  inputs: number, number
-
  name: subtraction
  tags: minus
  form: numvar = num - num
  example: equity = assets - liabilities
  output: number
  inputs: number, number
-
  name: multiplication
  tags: multiply, times
  form: numvar = num * num
  example: total = num_lines * price_per_line
  output: number
  inputs: number, number
-
  name: division (no remainder if both integers)
  tags: divide
  form: numvar = num / num
  example: estimate_per_line = total / num_lines
  output: number
  inputs: number, number
-
  name: convert object to string
  form: strvar = obj.to_s
  example: age_string = age.to_s
  output: string
  inputs: object
-
  name: convert object to string
  tags: interpolation, hash, curly, braces
  form: "strvar = \"#{obj}\""
  example: "age_string = \"#{age}\""
  output: string
  inputs: object
-
  name: convert number to string (2 decimal places)
  tags: percent, sprintf, printf, format
  form: "strvar = \"%.2f\" % num"
  example: "total_str = \"%.2f\" % total"
  output: string
  inputs: number
-
  name: add to number variable
  tags: increment, plus
  form: numvar += num
  example: total_charge += line_charge
  output: number
  inputs: number
-
  name: "output object and newline"
  tags: print
  form: puts obj
  example: puts first_name
  output: output
  inputs: object
-
  name: output object
  tags: print
  form: print obj
  example: 'print "#{first_name}\n"'
  output: output
  inputs: object
-
  name: "output object.inspect and newline"
  tags: print inspect
  form: p obj
  example: 'p first_name'
  output: output
  inputs: object
-
  name: conditional branching (1 leg)
  tags: then
  form: "if bool\n  statements\nend"
  example: "if n > 0\n  puts \"positive\"\nend"
  output: statements
  inputs: bool, statements
-
  name: conditional branching (2 legs)
  tags: then otherwise
  form: "if bool\n  statements\nelse\n  statements\nend"
  example: "if n > 0\n  puts \"positive\"\nelse\n  puts \"non-positive\"\nend"
  output: statements
  inputs: bool, statements
-
  name: conditional branching (3+ legs)
  tags: then otherwise
  form: "if bool\n  statements\nelsif bool\n  statements\nelse\n  statements\nend"
  example: "if n > 0\n  puts \"positive\"\nelsif n < 0\n  puts \"negative\"\nelse\n  puts \"zero\"\nend"
  output: statements
  inputs: bool, statements
