default['online-ruby-tutor']['user'] = 'deployer'
default['online-ruby-tutor']['group'] = 'deployer'
default['online-ruby-tutor']['database']['username'] = 'online_ruby_tutor'
default['online-ruby-tutor']['database']['password'] = 'online_ruby_tutor'
default['online-ruby-tutor']['database']['database'] = 'online_ruby_tutor'
default['online-ruby-tutor']['ruby_version'] = '1.9.3-p448'
default['postgresql']['password']['postgres'] = 'postgres'
